### ISSUE TITLE
detection.py  No loop matching

### ISSUE THREAD

**Issue by gauhar107** [cersar/3D_detection#12]
Hi, thanks for your work.
when I running detection.py, I have an Error as below, could you give any advice? 
Traceback (most recent call last):
  File "/home/3D_detection-master/detection.py", line 83, in <module>
    points2D = gen_3D_box(yaw, dims, cam_to_img, box_2D)
  File "/home/3D_detection-master/util/post_processing.py", line 112, in gen_3D_box
    center = compute_center(points3D, rot_M, cam_to_img, box_2D, inds)
  File "/home/3D_detection-master/util/post_processing.py", line 75, in compute_center
    result = solve_least_squre(W, y)
  File "/home/3D_detection-master/util/post_processing.py", line 28, in solve_least_squre
    U, Sigma, VT = np.linalg.svd(W)
  File "/home/.local/lib/python3.6/site-packages/numpy/linalg/linalg.py", line 1612, in svd
    u, s, vh = gufunc(a, signature=signature, extobj=extobj)
TypeError: No loop matching the specified signature and casting
was found for ufunc svd_n_f

**Comment by CaoBo1996** [comment]
yes，i found the same problem. So do you slove this problem finally?

**Comment by foofybuster** [comment]
Have you solved this error?

I solved it with adding `W = W.astype(np.float32)` before **the solve_least_squre function** in **post_processing.py** file
